config/routes.rb
Ifoundit::Application.routes.draw do
  resources :reports

  devise_for :users

  root 'landing#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  acts_as_gmappable
  has_attached_file :image, :styles => { :medium => "960x640>" }, :default_url => "/system/reports/images/missing.png"

  def gmaps4rails_address
    address
  end

  def gmaps4rails_marker_picture
    {
      "rich_marker" =>  "<div class='my-marker'><img src='http://cabargas.com/images/ifound-logo.png' width='45px' height='45px'/></div>"

    }
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reports
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController 
  http_basic_authenticate_with :name => "camilinda", :password => "caquita1234", :only => [:index]
  before_filter :authenticate_user!
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    @json = Report.all.to_gmaps4rails
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @json = Report.find(params[:id]).to_gmaps4rails
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @user = current_user.id
    
    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @report }
      else
        format.html { render action: 'new' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:image, :status, :item_type, :description, :age, :size, :height, :contexture, :raza, :colors, :skin, :medical, :med_detail, :sex, :address, :latitude, :longitude, :gmaps)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/landing/index.html.haml
=render('layouts/header')
.content
  .header=image_tag('mapa.png')
  .row{ :style => 'margin-top: -25px'}
    .large-6.columns
      =link_to "I lost it", new_report_path, :data => {:sts => "Lost"}, :class => "button alert expand"
    .large-6.columns
      =link_to "I found it", new_report_path, :data => {:sts => "Found"}, :class => "button success expand"
  .row
    .large-6.columns
      %h3 #Hack4Good
      %hr
      %p{ :style => 'text-align: justify;'} #hack4good is a unique global hackathon focusing solely on uniting the worlds greatest expert engineers, designers, product builders and entrepreneurs. Together we are helping make the world a better place by building projects that help humanity.
    .large-6.columns
      %h3 About the project
      %hr
      %p{ :style => 'text-align: justify;'} We use IT to help people searching/finding what they lose, in a public service provided by the community.
=render('layouts/footer')

app/views/landing/index_español.html.haml
=render('layouts/header')
.content
  .header=image_tag('mapa.png')
  .row{ :style => 'margin-top: -25px'}
    .large-6.columns
      =link_to "Perdí algo", new_report_path, :data => {:sts => "Lost"}, :class => "button alert expand"
    .large-6.columns
      =link_to "Encontré algo", new_report_path, :data => {:sts => "Found"}, :class => "button success expand"
  .row
    .large-6.columns
      %h3 #Hack4Good
      %hr
      %p{ :style => 'text-align: justify;'} #hack4good es un proyecto global único, dedicado únicamente a reunir a los más grandes ingenieros, diseñadores y emprendedores del mundo. Juntos estamos ayudando para lograr hacer del mundo un lugar mejor, ideando protectos que ayuden a la sociedad
    .large-6.columns
      %h3 Sobre el proyecto
      %hr
      %p{ :style => 'text-align: justify;'} Nuestra página, está orientada a la búsqueda de personas, animales o cosas. De esta forma si alguien pierde algo importante, se realizará un proceso de búsqueda que revise si alguien en algún lugar cerca de su locación, encontró algo con carácterísticas similares, para relacionarlos y ponerlos en contacto.
=render('layouts/footer')

app/views/landing/index_español.html.haml
=render('layouts/header')
.content
  .header=image_tag('mapa.png')
  .row{ :style => 'margin-top: -25px'}
    .large-6.columns
      =link_to "Perdí algo", new_report_path, :data => {:sts => "Lost"}, :class => "button alert expand"
    .large-6.columns
      =link_to "Encontré algo", new_report_path, :data => {:sts => "Found"}, :class => "button success expand"
  .row
    .large-6.columns
      %h3 #Hack4Good
      %hr
      %p{ :style => 'text-align: justify;'} #hack4good es un proyecto global único, dedicado únicamente a reunir a los más grandes ingenieros, diseñadores y emprendedores del mundo. Juntos estamos ayudando para lograr hacer del mundo un lugar mejor, ideando protectos que ayuden a la sociedad
    .large-6.columns
      %h3 Sobre el proyecto
      %hr
      %p{ :style => 'text-align: justify;'} Nuestra página, está orientada a la búsqueda de personas, animales o cosas. De esta forma si alguien pierde algo importante, se realizará un proceso de búsqueda que revise si alguien en algún lugar cerca de su locación, encontró algo con carácterísticas similares, para relacionarlos y ponerlos en contacto.
=render('layouts/footer')

app/views/layouts/_footer.html.haml
.row
  %hr
.row
  %p{ :style => 'text-align: center;'} Proudly developed by Camila L. Bustos & Felipe Cabargas M. - CC by-nc-nd - 2013 #Hack4Good

app/views/layouts/_footer_español.html.haml
.row
  %hr
.row
  %p{ :style => 'text-align: center;'} Orgullosamente desarrollado por Camila L. Bustos y Felipe Cabargas M. - CC by-nc-nd - 2013 #Hack4Good

app/views/layouts/_footer_español.html.haml
.row
  %hr
.row
  %p{ :style => 'text-align: center;'} Orgullosamente desarrollado por Camila L. Bustos y Felipe Cabargas M. - CC by-nc-nd - 2013 #Hack4Good

app/views/layouts/_header.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %a{ :href => "#{root_path}" }
        .logo=image_tag('logo.png')
  %section.top-bar-section
    %ul.right
      %li.divider
      -if user_signed_in?
        %li
          =link_to 'LOG OUT', destroy_user_session_path, :method => "delete"
      -else
        %li
          =link_to 'REGISTER', new_user_registration_path
        %li
          =link_to 'LOG IN', new_user_session_path

app/views/layouts/_header_español.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %a{ :href => "#{root_path}" }
        .logo=image_tag('logo.png')
  %section.top-bar-section
    %ul.right
      %li.divider
      -if user_signed_in?
        %li
          =link_to 'DESCONECTAR', destroy_user_session_path, :method => "delete"
      -else
        %li
          =link_to 'REGISTRO', new_user_registration_path
        %li
          =link_to 'INICIAR SESIÓN', new_user_session_path

app/views/layouts/_header_español.html.haml
%nav.top-bar
  %ul.title-area
    %li.name
      %a{ :href => "#{root_path}" }
        .logo=image_tag('logo.png')
  %section.top-bar-section
    %ul.right
      %li.divider
      -if user_signed_in?
        %li
          =link_to 'DESCONECTAR', destroy_user_session_path, :method => "delete"
      -else
        %li
          =link_to 'REGISTRO', new_user_registration_path
        %li
          =link_to 'INICIAR SESIÓN', new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/assets/favicon.png" rel="shortcut icon" type="image/x-icon">
    <link rel="apple-touch-icon" href="/assets/logo.png"/>
  	<title><%= content_for?(:title) ? yield(:title) : "IFoundIt" %></title>

    <script type="text/javascript" src="//maps.google.com/maps/api/js?v=3.5&sensor=false&amp;libraries=geometry"></script>
    <script type="text/javascript" src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.5/src/markerclusterer_packed.js"></script>
    <%= stylesheet_link_tag "gmaps4rails" %>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
  <%= yield :scripts %>
</html>

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :item_type %><br>
    <%= f.text_field :item_type %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :contexture %><br>
    <%= f.text_field :contexture %>
  </div>
  <div class="field">
    <%= f.label :raza %><br>
    <%= f.text_field :raza %>
  </div>
  <div class="field">
    <%= f.label :colors %><br>
    <%= f.text_field :colors %>
  </div>
  <div class="field">
    <%= f.label :skin %><br>
    <%= f.text_field :skin %>
  </div>
  <div class="field">
    <%= f.label :medical %><br>
    <%= f.check_box :medical %>
  </div>
  <div class="field">
    <%= f.label :med_detail %><br>
    <%= f.text_field :med_detail %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div> 
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.hidden_field :user_id, :value => @current_user.id %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br>
    <%= f.check_box :gmaps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_object_detail.html.haml
.large-12.columns
  .panel  
    %h3 DESCRIPTION
    %p= @report.description
    %hr
    %h3 IMAGE OF THE OBJECT
    %p
      =image_tag(@report.image.url)
    %hr
    %h3 LAST SEEN AT
    %p
      = @report.address

app/views/reports/_person_detail.html.haml
.large-8.columns
  %h3 DESCRIPTION
  %p= @report.description
.large-4.columns
  .panel
    %p
      =image_tag(@report.image.url)
    %p
      %strong Sex:
      = @report.sex
    %p
      %strong Age:
      = @report.age
    %p
      %strong Height:
      = @report.height
    %p
      %strong Contexture:
      = @report.contexture
    %p
      %strong Skin:
      = @report.skin
    %hr
    -if @report.medical == true
      %span.alert.label NEEDS MEDICAL CARE
      %p
        %strong Medical Details
        = @report.med_detail
    -else
      %span.success.label HEALTHY PERSON
    %hr
    %p
      %strong Last seen at:
      = @report.address
    %hr
    -if @report.status == 'Found'
      %a.button.expand I RECOGNIZE HIM/HER !
    -elsif @report.status == 'Lost'
      %a.button.expand I SAW HIM/HERl !

app/views/reports/_pet_detail.html.haml
.large-8.columns
  %h3 DESCRIPTION
  %p= @report.description
.large-4.columns
  .panel
    %p
      =image_tag(@report.image.url)
    %p
      %strong Species:
      = @report.raza
    %p
      %strong Sex:
      = @report.sex
    %p
      %strong Age:
      = @report.age
    %p
      %strong Size:
      = @report.size
    %p
      %strong Race:
      = @report.skin
    %hr
    %p
      %strong Last seen at:
      = @report.address

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<h1>Listing reports</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Type</th>
      <th>Description</th>
      <th>Age</th>
      <th>Size</th>
      <th>Height</th>
      <th>Contexture</th>
      <th>Raza</th>
      <th>Colors</th>
      <th>Skin</th>
      <th>Medical</th>
      <th>Med detail</th>
      <th>Sex</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Gmaps</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.status %></td>
        <td><%= report.item_type %></td>
        <td><%= report.description %></td>
        <td><%= report.age %></td>
        <td><%= report.size %></td>
        <td><%= report.height %></td>
        <td><%= report.contexture %></td>
        <td><%= report.raza %></td>
        <td><%= report.colors %></td>
        <td><%= report.skin %></td>
        <td><%= report.medical %></td>
        <td><%= report.med_detail %></td>
        <td><%= report.sex %></td>
        <td><%= report.address %></td>
        <td><%= report.latitude %></td>
        <td><%= report.longitude %></td>
        <td><%= report.gmaps %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>


<%= gmaps("markers" => {"data" => @json, "options" => {"rich_marker" => true } }) %>

app/views/reports/new.html.haml
=render('layouts/header')
.content{ :style => 'margin-top: 100px; margin-bottom: 100px;'}
  .row
    %h3 I found/lost something or someone
    %hr
  .row
    =form_for :report, :url => {:controller => 'reports', :action => 'create'} do |f|
      -if 'data-sts' == "Lost"
        =f.hidden_field :status, :value => "Lost"
      -else
        =f.hidden_field :status, :value => "Found"
      - if @report.errors.any?
        .hola
          %h4
            Tu formulario contiene
            = pluralize(@report.errors.count, "error(es)")
          %blockquote
            - @report.errors.full_messages.each do |msg|
              %p= msg
      .row
        .large-12.columns
          =f.label :item_type
          =f.select(:item_type, options_for_select(['Select type','Person', 'Pet', 'Object']))
      %hr
      .person{ :style => 'display: none;'}
        .row
          .large-2.columns
            =f.label :age
            =f.select(:age, options_for_select(["--", "0-2 years", "3-5 years", "6-9 years", "10-13 years", "14-16 years", "17-19 years", "20-24 years", "25-30 years", "31-35 years", "36-40 years", "+40 years", "+50 years", "+60 years"]))
          .large-2.columns
            =f.label :sex
            =f.select(:sex, options_for_select(['N.D.', 'MALE', 'FEMALE']))
          .large-1.columns
            =f.label :height
            =f.text_field(:height, placeholder: "Ex: 1.75")
          .large-1.columns
            =f.label :contexture
            =f.select(:contexture, options_for_select(['--', 'Skinny', 'Regular', 'Fat']))
          .large-1.columns
            =f.label :medical
            =f.check_box(:medical)
          .large-3.columns
            =f.label :med_detail
            =f.text_field(:med_detail, placeholder: "Ex: Alzheimer, Diabetes, Autism")
          .large-2.columns
            =f.label :skin
            =f.text_field(:skin, placeholder: "Ex: White, Black")
      .pet{ :style => 'display: none;'}
        .row
          .large-3.columns
            =f.label :raza
            =f.select(:raza, options_for_select(['--','CAT', 'DOG', 'OTHER']))
          .large-3.columns
            =f.label :size
            =f.select(:size, options_for_select(['--','Small', 'Normal', 'Big', 'Huge']))
          .large-3.columns
            =f.label :colors
            =f.text_field(:colors, placeholder: "Ex: Orange w/ black stripes")
          .large-3.columns
            =f.label :skin
            =f.text_field(:skin, placeholder: "Ex: Persian, Yorkshire, Schnauzer, Angora, etc; if you don't know, please write 'Unknown'")
      .row
        .large-4.columns
          =f.label :address
          =f.text_field(:address, placeholder: "Ex: Av.Vitacura 2771, Las Condes, Santiago, Chile")
        .large-2.columns
          =f.label :image
          =f.file_field :image
        .large-6.columns
          =f.label :description
          =f.text_area(:description, placeholder: "Does this person respond to any name?, Describe the subject in a few lines to see if WE have any matches.")
      .row    
        =f.submit

app/views/reports/show.html.haml
=render('layouts/header')
.content{ :style => 'margin-top: 100px; margin-bottom: 100px;'}
  .row
    = gmaps("markers" => {"data" => @json, "options" => {"rich_marker" => true, "auto_adjust" => true } })
  .row
    %h1 
      CURRENT STATUS
      -if @report.status == "Lost"
        %span.alert.radius.label LOST
      -elsif @report.status == "Found"
        %span.success.radius.label FOUND
      -else
        %span.secondary.radius.label CLOSED
    %hr
  .row
    -if @report.item_type == "Person"
      =render('person_detail')
    -elsif @report.item_type == "Pet"
      =render('pet_detail')
    -else
      =render('object_detail')
=render('layouts/footer')

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>